/*
    THIS FILE IS GENERATED BY AVERSION. 
    IT SHOULD PROBABLY NOT BE EDITED DIRECTLY.
*/

using System;
using System.Reflection;
using System.Runtime.InteropServices;

// General Information about an assembly is controlled through the following 
// set of attributes. Change these attribute values to modify the information
// associated with an assembly.
[assembly: AssemblyTitle("ICM.Rebus.Async")]
[assembly: AssemblyDescription("Experimental async/await-based request/reply API for Rebus")]
[assembly: AssemblyConfiguration("")]
[assembly: AssemblyCompany("mookid8000,michalsteyn")]
[assembly: AssemblyProduct("Rebus.Async")]
[assembly: AssemblyCopyright("Copyright 2012-2016")]
[assembly: AssemblyTrademark("")]
[assembly: AssemblyCulture("")]

// Setting ComVisible to false makes the types in this assembly not visible 
// to COM components.  If you need to access a type in this assembly from 
// COM, set the ComVisible attribute to true on that type.
[assembly: ComVisible(false)]
[assembly: CLSCompliant(true)]

// The following GUID is for the ID of the typelib if this project is exposed to COM
[assembly: Guid("206bfbfd-dd80-4bac-a50a-caee097da9ad")]

// Version information for an assembly consists of the following four values:
//
//      Major Version
//      Minor Version 
//      Build Number
//      Revision
//
// You can specify all the values or you can default the Build and Revision Numbers 
// by using the '*' as shown below:
// [assembly: AssemblyVersion("1.0.*")]
[assembly: AssemblyVersion("3.0.2.0")]
